apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongo-nodeport-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000 #30000-65000 port range default in minikube
  selector:
    app: mongodb
  type: NodePort
status:
  loadBalancer: {}